# Generated by Django 4.2.2 on 2023-07-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_City', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phno', models.BigIntegerField()),
                ('customer_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.arrivalcities')),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_number', models.CharField(max_length=100)),
                ('Cost', models.BigIntegerField()),
                ('Date', models.DateField()),
                ('Arrival_time', models.TimeField()),
                ('Arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.arrivalcities')),
                ('Destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.destinationcities')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Phno', models.BigIntegerField()),
                ('Booking_status', models.BooleanField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.customer')),
                ('Flight_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.flightdetails')),
            ],
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='Flight_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.flights'),
        ),
    ]
