# Generated by Django 4.2.2 on 2023-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationcities',
            name='D_City',
            field=models.CharField(max_length=100),
        ),
    ]
